appname = nuxeo_mid
httpport = ${PORT_NUXEO_MID}
runmode = prod
autorender = false
copyrequestbody = true

parameterStore = ${PARAMETER_STORE}
user = ${USER_NUXEO}
password = ${PASSWORD_NUXEO}
urlNuxeo = documental.portaloas.udistrital.edu.co:443/nuxeo/site/api/v1/